### ISSUE TITLE
Actionsheet hiding in cydia

### ISSUE THREAD

**Issue by AbuMotlq** [tomaszpoliszuk/AlertController#3] opened 2020-08-09 19:01 UTC
When I set the Action Sheet style to (Alert), the action sheet menus do not appear in Cydia.When I want remove any tweak I can't.In my iPadAir 2 ios13.5

**Comment by tomaszpoliszuk** [comment] 2020-08-09 23:04
This is duplicate of #2 Issue.

I'm closing this one but please follow this instruction:

[Could you contact me using option in package manager (in Cydia you can tap on author field and then again on author field) - it will autogenerate additional information for me.](https://github.com/tomaszpoliszuk/AlertController/issues/2#issuecomment-669128930)

[Please add information that it's you (or link to this issue).](https://github.com/tomaszpoliszuk/AlertController/issues/2#issuecomment-669128930)

and follow fixing process of this issue in that active one (#2)

**Closed as completed by tomaszpoliszuk** 2020-08-09 23:04 UTC
Labels: duplicate
